# Generated by Django 4.2.4 on 2023-08-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان در url'),
        ),
    ]
