# Generated by Django 4.2.4 on 2023-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='عنوان سایت')),
                ('site_url', models.CharField(max_length=100, verbose_name='دامنه سایت')),
                ('about_site', models.CharField(max_length=100, verbose_name='درباره من سایت')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='فکس')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('copy_right', models.CharField(max_length=100, verbose_name='متن کپی رایت')),
                ('site_logo', models.ImageField(upload_to='images/site_setting', verbose_name='لوکو سایت')),
                ('is_main_site', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات اصلی',
                'verbose_name_plural': 'تنظیمات اصلی سایت',
            },
        ),
    ]
