# Generated by Django 4.2.4 on 2023-08-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_footerlinkbox_alter_sitesetting_about_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.CharField(max_length=100, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('descriptions', models.TextField(verbose_name='توضیحات اسلایدر')),
                ('images', models.ImageField(upload_to='images/slider', verbose_name='تضویز اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'لینک فوتر', 'verbose_name_plural': 'لینک های فوتر'},
        ),
        migrations.AlterModelOptions(
            name='footerlinkbox',
            options={'verbose_name': 'دسته بندی لینک فوتر', 'verbose_name_plural': 'دسته بندی های لینک های فوتر'},
        ),
    ]
