# Generated by Django 4.2.4 on 2023-08-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_slider_alter_footerlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='تایید شده / نشده'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ImageField(upload_to='images/slider', verbose_name='تصویر اسلایدر'),
        ),
    ]
