# Generated by Django 4.2.4 on 2023-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_slider_is_active_alter_slider_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال شده / نشده'),
        ),
    ]
