# Generated by Django 4.2.4 on 2023-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_alter_slider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.CharField(max_length=100, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/ عیرفعال')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه توضیحات محصولات'), ('about_us', 'صفحه درباره ما')], max_length=100, verbose_name='جایگاه نمایشی')),
            ],
        ),
    ]
