# Generated by Django 4.2.4 on 2023-08-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_sitebanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'verbose_name': 'بنر تبلیغاتی', 'verbose_name_plural': 'بنر های تبلیغاتی'},
        ),
    ]
