# Generated by Django 4.2.4 on 2023-08-22 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_article_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 8, 22), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
