# Generated by Django 4.2.4 on 2023-08-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_articlecommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommend',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecommend', verbose_name='والد'),
        ),
    ]
